### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by tompointexe** [VizuaaLOG/pterodactyl-php#1]
Would be great if we have the ability use the lib without having to require it in composer

**Comment by VizuaaLOG** [comment]
Could I ask the need for using it without Composer? Composer is very common for managing packages and would suggest using it wherever possible to help manage the dependencies you're loading in.

**Comment by tompointexe** [comment]
Personaly i would have used it for debuging , but i finaly managed to debug everything and it works now :) thanks for responce :)
