### ISSUE TITLE
The environment field must be present.

### ISSUE THREAD

**Issue by deamvw** [VizuaaLOG/pterodactyl-php#2]
Hello,

When I want to create a server, the error log says: "The environment field must be present.". If I add a value with "null" it says " The environment must be an array.".

What do I need to fill in, in the environment value?

This is my code:

```
$startup = ('if [[ -d .git ]] && [[ {{AUTO_UPDATE}} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/{{BOT_JS_FILE}}');

$data = array(
  "user" => "1",
  "node" => "1",
  "name" => "TEST-API",
  "cpu" => "100",
  "memory" => "128",
  "disk" => "0",
  "nest" => "5",
  "egg" => "16",
  "docker_image" => "ghcr.io/parkervcp/yolks:nodejs_16",
  "startup" => "$startup"
);

$server = $panel->servers->create($data);
```

Thanks,
Dean

**Comment by deamvw** [comment]
Hello,

I have found it out.
But how can I configure the default allocation?

 Thanks,
Dean

**Comment by VizuaaLOG** [comment]
Hey 👋 ,

This library doesn't provide any default configuration, it's purely for having a more object orientated interface for the Pterodactyl API. All values passed to the various methods expect the same data as what the Pterodactyl API requests.

I don't use Pterodactyl or this library anymore so I'm not sure if you're able to configure a default allocation within the panel interface.
